config/routes.rb
Demo::Application.routes.draw do

resources :sessions
resources :questions do
	resources :answers , only: [:create] do
  		resources :votes , only: [:create]do
  			collection do 
  				post :create
  			end 
  		end
  	end
end
  get "home" => "questions#index"
  get "log_out" => "sessions#destroy"
  get "log_in" => "sessions#new"

end

app/models/add_user_id_to_answer.rb
class AddUserIdToAnswer < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/add_user_id_to_vote.rb
class AddUserIdToVote < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  has_many :votes , dependent: :destroy
  attr_accessible :answer
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :user
  has_many :answers , dependent: :destroy
  attr_accessible :question
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password
  has_many :questions
  has_many :answers
  has_many :votes
  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && password == user.password
      user
    else
      nil
    end
  end
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :answer
  belongs_to :user
  attr_accessible :votes
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
	before_filter :question_answer ,only: [:create]

	def create
		if @answer.save 
		   redirect_to home_path , :notice => "Thanks for the answer"
		else 
		   redirect_to home_path , :notice => "Answer Not posted"
		end
 	end

 	private
 	def question_answer
 		@answer = Answer.new(params[:answer])
		@answer.question = Question.find(params[:question_id])
		@answer.user_id = session[:user_id]
 	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user

	private

	def current_user
	  @current_user ||= User.find(session[:user_id]) if session[:user_id]
	end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_filter :question_param , only: [:destroy, :show]

  def new
  	@question = Question.new
  end
    
    
  def create
    	@question = Question.new(params[:question])
    	if @question.save
    		redirect_to home_path , :notice => "Your question is posted"
    	else
    		render 'new'
    	end
  end

    
  def destroy
    	@question.destroy
    	redirect_to @question , :notice => "You deleted a question"
  end

  def show
  end

  def index
    @question = Question.all
  end

  private
  def question_param
      @question = Question.find(params[:id])
  end
    
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user = User.authenticate(params[:email], params[:password])
    if user
      session[:user_id] = user.id
      redirect_to home_path, :notice => "Logged in!"
    else
      flash.now.alert = "Invalid email or password"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to home_path, :notice => "Logged out!"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController

	before_filter :vote_param ,only: [:create]

	def create
		if @vote.save
		   redirect_to home_path, :notice => "Thanks for Voting"
		else 
		   redirect_to home_path
		end 
 	end

 	private
 	 	def vote_param
 		if current_user.answers.where("id = #{params[:answer_id]}").count > 0
 	 		redirect_to home_path, :notice => "You could not like your own post"
 		elsif current_user.votes.where("answer_id = #{params[:answer_id]}").count > 0
 	 		redirect_to home_path, :notice => "Already Liked"
 		else
 			@vote = Vote.new(params[:vote])
			@vote.votes = 1
 			@vote.answer = Answer.find(params[:answer_id])
			@vote.user_id = current_user	
 		end
 	end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/answers/_form.html.erb
<div class="render_form">
<% @question = question
   @answer = answer 
 %>

<h2>Add your answer:</h2>

<%= form_for(@answer, :url => question_answers_path(@answer.question), :method => 'post') do |f| %>
  <div class="field">
    <%= f.text_area :answer %>
  </div>
  <div class="actions">
    <%= f.submit "Post Answer"%>
  </div>
<% end %>

</div>

app/views/comments/new.html.erb
<h1>Comments#new</h1>
<p>Find me in app/views/comments/new.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Demo</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="logo_main">  	
    <%= image_tag("logo.png" , class: "style_image")%>
  </div>
  <div class="head_title">
    <h1>FixIt</h1>
  </div>
  <div id="user_nav">
    <% if current_user %>
      <div class="post_question">
        <%= link_to 'Post Question', new_question_path %>
      </div>| 
        Hi <%= current_user.email %>
        <%= link_to "Log out", log_out_path %>
      <% else %>
        <%= link_to 'Log In', new_session_path %>
      <% end %>
  </div>
  <div class = "flash_message">
    <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, :id => "flash_#{name}" %>
  <% end %>
  </div>

  <%= yield %>

</body>
</html>

app/views/questions/edit.html.erb
<div class="panel">
	<p>My Question</p>
	<div class="login">
		<%= link_to 'Home', home_path %> |
<%= link_to 'Answer', edit_question_path(@question) %> 

	</div>
 <%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@question.errors.count, "error") %> prohibited
        this question from being saved:</h2>
    <ul>
    <% @question.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
 
  <div class="question">
<br>    <%= f.text_area :question %>
  </div>
  
  <div class="question_submit">
    <%= f.submit %>
  </div>
<% end %>

app/views/questions/index.html.erb
<% provide(:title,'Sign In') %>
<div class="panel">
	<p>My Articles</p>
</div>
 
<table>
  <tr>
    <th>Question</th>
    <th>View/Answer</th>
    <th>Delete Post</th>
  </tr>
 
  <% @question.each do |question| %>
    <tr>
		<td><%= question.question %></td>
    <% if current_user %>
      <td><%= link_to 'View / Answer', question_path(question) %></td>
      <td><%= link_to 'Delete Question', question_path(question),
                    method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% else %>
    <%= link_to 'Log In', new_session_path %>
  <% end %>
    </tr>
  <% end %>
</table>

app/views/questions/new.html.erb
	<div class="logo_main">   
	  <%= image_tag("logo.png" , class: "style_image")%>
	</div>
	<div class="head_title">
	  <h1>FixIt</h1>
	</div>
	<div class="panel">
	  <p>New Question</p>
	  <div class="login">
	  <%= link_to 'Back', home_path %>    
	  </div>
	</div>
	  <% if current_user %>

	<div class="new_content">

	<%= form_for :question, url: questions_path do |f| %>
	  <% if @question.errors.any? %>
	  <div id="error_explanation">
	    <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>
	    <ul>
	    <% @question.errors.full_messages.each do |msg| %>
	      <li><%= msg %></li>
	    <% end %>
	    </ul>
	  </div>
	  <% end %>
	  <p>
	    <%= f.label :question %><br>
	    <%= f.text_area :question %>
	  </p>
	 
	  <p>
	    <%= f.submit %>
	  </p>
	<% end %>

	 </div>
	<% else %>
	<div class='login_content' >
	Login to continue
	</div>
	<% end %>

app/views/questions/show.html.erb
<div class="panel">
	<p>My Articles</p>
	<div class="login">
		<%= link_to 'Home', home_path %> |

	</div>

</div>
 <div class="show_article">
<p>
  <strong>Question:</strong>
  <%= @question.question %>
</p>
</div>
<div class="answer">
<h2>Answers</h2>
<% @question.answers.each do |answer| %>
 
  <p>
    <b>Answer:</b>
    <%= answer.answer %> <br><br>Posted on 	
	<%= answer.created_at.to_date.iso8601%> by 
	<%= User.find(answer.user_id).email %>
<div class = "votes">
<%= render :partial => 'votes/form', :locals => {:answer => answer, :vote => answer.votes.build} %>
  </div></p>
<% end %>
  <% if current_user %>
<%= render :partial => 'answers/form', :locals => { :question => @question, :answer => @question.answers.build } %>
<% else %>
Login to answer
<% end %>
</div>

app/views/votes/_form.html.erb
<%  @answer = answer 
	@vote = vote	%>
	<%= form_for(@vote,:url => question_answer_votes_path(@answer.question,@vote.answer), :method => 'post') do |f| %>
		<%= f.submit "UpVote" %>
	<%= Vote.find(:all, :conditions => {:answer_id => @answer.id}).count %> Vote(s)
	<%end %>